// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SecurityJournal is the predicate function for securityjournal builders.
type SecurityJournal func(*sql.Selector)

// SecurityPosition is the predicate function for securityposition builders.
type SecurityPosition func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
